# Generated by Django 4.1.2 on 2023-02-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalledger',
            old_name='updated_date',
            new_name='update_date',
        ),
    ]
